#include <glim/util/mapcleaner_exporter.hpp>

#include <filesystem>
#include <fstream>
#include <iomanip>
#include <sstream>

#include <boost/format.hpp>
#include <Eigen/Geometry>

#include <glim/util/pcd_exporter.hpp>

namespace glim {
namespace {

void write_tum_frame(std::ofstream& ofs, const double stamp, const Eigen::Isometry3d& pose) {
  const Eigen::Quaterniond quat(pose.linear());
  const Eigen::Vector3d trans(pose.translation());

  ofs << boost::format("%.9f %.6f %.6f %.6f %.6f %.6f %.6f %.6f")
           % stamp
           % trans.x()
           % trans.y()
           % trans.z()
           % quat.x()
           % quat.y()
           % quat.z()
           % quat.w()
      << std::endl;
}

std::string scan_filename(const std::size_t scan_id) {
  std::ostringstream ss;
  ss << std::setw(6) << std::setfill('0') << scan_id << ".pcd";
  return ss.str();
}

void write_loader_yaml(const std::string& output_dir, const std::size_t num_scans) {
  std::ofstream ofs(output_dir + "/loader_glim.yaml");

  ofs << "# Generated by GLIM rover core MapCleaner exporter\n";
  ofs << "loader:\n";
  ofs << "  pcds_dir: \"" << output_dir << "/scans\"\n";
  ofs << "  pose_file: \"" << output_dir << "/traj_lidar.txt\"\n";
  ofs << "  kitti_calibration_file: \"\"\n";
  ofs << "  start: 0\n";
  ofs << "  end: " << (num_scans == 0 ? -1 : static_cast<long long>(num_scans) - 1) << "\n";
  ofs << "  format: \"glim\"\n";
  ofs << "\n";
  ofs << "map_cleaner:\n";
  ofs << "  save_dir: \"" << output_dir << "/result\"\n";
}

void write_readme(const std::string& output_dir, const std::size_t num_scans) {
  std::ofstream ofs(output_dir + "/README.md");

  ofs << "# GLIM to MapCleaner export\n\n";
  ofs << "Generated files:\n\n";
  ofs << "- `scans/*.pcd`: individual GLIM keyframe clouds in LiDAR-local coordinates.\n";
  ofs << "- `traj_lidar.txt`: TUM-style LiDAR poses aligned one-to-one with `scans/*.pcd`.\n";
  ofs << "- `loader_glim.yaml`: MapCleaner loader snippet.\n\n";
  ofs << "Number of scans: " << num_scans << "\n";
}

bool write_scan(
    const std::string& path,
    const gtsam_points::PointCloud& cloud) {
  if (cloud.size() == 0) {
    return false;
  }

  if (cloud.has_intensities()) {
    return save_pcd_xyzi(path, cloud);
  }

  return save_pcd_xyz(path, cloud);
}

}  // namespace

bool export_mapcleaner_dataset(
    const std::string& output_dir,
    const std::vector<SubMap::Ptr>& submaps,
    MapCleanerExportStats* stats) {
  MapCleanerExportStats local_stats;
  local_stats.submaps = submaps.size();

  std::filesystem::create_directories(output_dir);
  std::filesystem::create_directories(output_dir + "/scans");
  std::filesystem::create_directories(output_dir + "/result");

  std::ofstream traj_lidar_ofs(output_dir + "/traj_lidar.txt");
  if (!traj_lidar_ofs) {
    if (stats) {
      *stats = local_stats;
    }
    return false;
  }

  std::size_t scan_id = 0;

  for (const auto& submap : submaps) {
    if (!submap) {
      continue;
    }

    const auto* keyframes = submap->get_custom_data<MapCleanerKeyframes>(MAPCLEANER_KEYFRAMES_KEY);

    if (keyframes && !keyframes->empty()) {
      local_stats.submaps_with_keyframes++;
      local_stats.keyframes_seen += keyframes->size();

      for (const auto& keyframe : *keyframes) {
        if (!keyframe.cloud || keyframe.cloud->size() == 0) {
          local_stats.skipped_empty_frames++;
          continue;
        }

        const std::string filename = scan_filename(scan_id);
        const std::string pcd_path = output_dir + "/scans/" + filename;

        if (!write_scan(pcd_path, *keyframe.cloud)) {
          local_stats.skipped_empty_frames++;
          continue;
        }

        const Eigen::Isometry3d T_world_lidar =
          submap->T_world_origin * keyframe.T_origin_lidar;

        write_tum_frame(traj_lidar_ofs, keyframe.stamp, T_world_lidar);

        scan_id++;
        local_stats.scans_written++;
        local_stats.poses_written++;
      }

      continue;
    }

    // Fallback for passthrough / future dumps that actually keep frame clouds.
    if (submap->frames.empty()) {
      continue;
    }

    const Eigen::Isometry3d T_world_endpoint_L =
      submap->T_world_origin * submap->T_origin_endpoint_L;

    const Eigen::Isometry3d T_odom_imu0 = submap->frames.front()->T_world_imu;

    for (const auto& frame : submap->frames) {
      local_stats.frames_seen++;

      if (!frame || !frame->frame || frame->frame->size() == 0) {
        local_stats.skipped_empty_frames++;
        continue;
      }

      const Eigen::Isometry3d T_world_imu =
        T_world_endpoint_L * T_odom_imu0.inverse() * frame->T_world_imu;

      const Eigen::Isometry3d T_world_lidar =
        T_world_imu * frame->T_lidar_imu.inverse();

      const std::string filename = scan_filename(scan_id);
      const std::string pcd_path = output_dir + "/scans/" + filename;

      if (!write_scan(pcd_path, *frame->frame)) {
        local_stats.skipped_empty_frames++;
        continue;
      }

      write_tum_frame(traj_lidar_ofs, frame->stamp, T_world_lidar);

      scan_id++;
      local_stats.scans_written++;
      local_stats.poses_written++;
    }
  }

  write_loader_yaml(output_dir, local_stats.scans_written);
  write_readme(output_dir, local_stats.scans_written);

  if (stats) {
    *stats = local_stats;
  }

  return true;
}

}  // namespace glim
